# Generated by Django 4.0.2 on 2022-03-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_alter_register_pic_all_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='pic',
            field=models.ImageField(default='logo9.png', upload_to='Profile Pic'),
        ),
    ]
