# Generated by Django 4.0.2 on 2022-03-15 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0011_department_alter_register_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_course',
            name='uid',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.RemoveField(
            model_name='register',
            name='pic',
        ),
        migrations.DeleteModel(
            name='All_Course',
        ),
    ]
