# Generated by Django 4.0.2 on 2022-03-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0012_remove_all_course_uid_delete_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='pic',
            field=models.ImageField(default='logo14.png', upload_to='Profile Pic'),
        ),
    ]
