# Generated by Django 4.0.2 on 2022-03-16 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0016_alter_register_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Myapp.register'),
        ),
        migrations.AlterField(
            model_name='register',
            name='pic',
            field=models.ImageField(default='logo10.png', upload_to='Profile Pic'),
        ),
    ]
