# Generated by Django 4.0.2 on 2022-03-27 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0020_alter_register_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='pic',
            field=models.ImageField(default='logo4.png', upload_to='Profile Pic'),
        ),
        migrations.CreateModel(
            name='Add_Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('material', models.FileField(upload_to='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.all_course')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.register')),
            ],
        ),
    ]
