# Generated by Django 4.0.2 on 2022-03-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdhyanApp', '0006_rename_users_user'),
        ('Myapp', '0021_alter_register_pic_add_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_course',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='views', to='AdhyanApp.User'),
        ),
    ]
