# Generated by Django 4.0.3 on 2022-04-08 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdhyanApp', '0006_rename_users_user'),
        ('Myapp', '0024_alter_register_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ManyToManyField(related_name='Cart', to='Myapp.all_course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdhyanApp.user')),
            ],
        ),
    ]
