# Generated by Django 4.0.2 on 2022-04-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0029_alter_all_course_codiscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart',
            field=models.ManyToManyField(related_name='Cart', to='Myapp.All_Course'),
        ),
    ]
