# Generated by Django 4.0.2 on 2022-04-12 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdhyanApp', '0006_rename_users_user'),
        ('Myapp', '0030_delete_review_alter_cart_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.all_course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdhyanApp.user')),
            ],
        ),
    ]
