# Generated by Django 4.0.2 on 2022-03-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(max_length=150)),
                ('password', models.CharField(max_length=15)),
                ('pic', models.FileField(default='avtar.png', upload_to='Profile Pic')),
            ],
        ),
    ]
