# Generated by Django 4.0.2 on 2022-03-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdhyanApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=13)),
                ('des', models.TextField(max_length=200)),
                ('enq_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
