# Generated by Django 4.0.3 on 2022-03-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdhyanApp', '0004_alter_enquiry_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=15)),
                ('dob', models.DateField()),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(max_length=150)),
                ('password', models.CharField(max_length=15)),
                ('pic', models.FileField(default='avtar.png', upload_to='Profile Pic')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
